## get
GET 127.0.0.1:8080/destination
Accept: application/json
Content-Type: application/json

### get one
GET 127.0.0.1:8080/destination/1
Accept: application/json
Content-Type: application/json

### create
PUT 127.0.0.1:8080/destination
Accept: application/json
Content-Type: application/json

{
  "name" :  "Beach Pelabuhan Ratu",
  "description" : "Pantai",
  "price" :  15000.0,
  "country_id" : 1,
  "photos" :  "a.jpg",
  "insurance" : true,
  "refundable" : true,
  "vat" : 2.4
}

### create
PUT 127.0.0.1:8080/destination
Accept: application/json
Content-Type: application/json

{
  "name" :  "Beach Pelabuhan Ratu",
  "description" : "Pantai",
  "price" :  15000.0,
  "country_id" : 1,
  "photos" :  "a.jpg",
  "insurance" : true,
  "refundable" : true,
  "vat" : 2.4
}